In [110]:
import numpy as np
import numpy.testing as npt
import pandas as pd
import diff_classifier.msd as msd
import pandas.util.testing as pdt
from scipy import interpolate
import diff_classifier.features as ft
import math

In [162]:
frames = 10
d = {'Frame': np.linspace(0, frames, frames),
     'X': np.sin(np.linspace(0, frames, frames)+3),
     'Y': np.cos(np.linspace(0, frames, frames)+3),
     'Track_ID': np.ones(frames)}
df = pd.DataFrame(data=d)
df = msd.all_msds2(df, frames=frames+1)

In [165]:
ft.msd_ratio(df, 1, 9)

-0.09876543209876543

In [80]:
d4

array([-0.54402111,  0.83907153])

In [164]:
frames = 10
d = {'Frame': np.linspace(0, frames, frames),
     'X': np.linspace(0, frames, frames)+5,
     'Y': np.linspace(0, frames, frames)+3,
     'Track_ID': np.ones(frames)}
df = pd.DataFrame(data=d)
df = msd.all_msds2(df, frames=frames+1)

In [161]:
ft.efficiency(df)

(10.0, 1.0)

In [257]:
d = {'Frame': [0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
     'Track_ID': [1, 1, 1, 1, 1, 2, 2, 2, 2, 2],
     'X': [0, 0, 1, 1, 2, 1, 1, 2, 2, 3],
     'Y': [0, 1, 1, 2, 2, 0, 1, 1, 2, 2]}
df = pd.DataFrame(data=d)
dfi = msd.all_msds2(df, frames = 5)
feat = ft.calculate_features(dfi)

In [258]:
dfi

Frame  Gauss  MSDs  Track_ID    X    Y
0    0.0   0.00   0.0       1.0  0.0  0.0
1    1.0   0.50   1.0       1.0  0.0  1.0
2    2.0   0.25   2.0       1.0  1.0  1.0
3    3.0   0.34   5.0       1.0  1.0  2.0
4    4.0   0.25   8.0       1.0  2.0  2.0
5    0.0   0.00   0.0       2.0  1.0  0.0
6    1.0   0.50   1.0       2.0  1.0  1.0
7    2.0   0.25   2.0       2.0  2.0  1.0
8    3.0   0.34   5.0       2.0  2.0  2.0
9    4.0   0.25   8.0       2.0  3.0  2.0

In [259]:
feat

AR     D_fit  MSD_ratio  Track_ID     X     Y     alpha  asymmetry1  \
0  4.0  0.170519  -0.266667       1.0  0.75  1.25  1.779337    0.944024   
1  4.0  0.170519  -0.266667       2.0  1.75  1.25  1.779337    0.944024   

   asymmetry2  asymmetry3  boundedness  efficiency  elongation  fractal_dim  \
0        0.12    0.369143         0.25         2.0        0.75     1.333333   
1        0.12    0.369143         0.25         2.0        0.75     1.333333   

   frames  kurtosis  straightness  trappedness  
0     5.0  1.166667      0.707107    -0.152585  
1     5.0  1.166667      0.707107    -0.152585

In [287]:
frames = 6
d = {'Frame': np.linspace(0, frames, frames),
     'X': [0, 1, 1, 2, 2, 3],
     'Y': [0, 0, 1, 1, 2, 2],
     'Track_ID': np.ones(frames)}
df = pd.DataFrame(data=d)
df = msd.all_msds2(df, frames=frames+1)
assert ft.aspectratio(df)[0:2] == (3.9000000000000026, 0.7435897435897438)
npt.assert_almost_equal(ft.aspectratio(df)[2], np.array([1.5, 1. ]))

In [284]:
ft.aspectratio(df)[2]

array([1.5, 1. ])

In [285]:
np.array([1.5, 1])

array([1.5, 1. ])