In [57]:
import numpy as np
import pandas as pd
import numpy.ma as ma
from scipy.optimize import curve_fit

#modulef = '/home/ubuntu/source/diff-classifier/diff_classifier/'
modulef = 'C:/Users/koolk/Desktop/diff-classifier/diff_classifier/'
import sys
sys.path.insert(0, modulef)

from utils import csv_to_pd
from msd import nth_diff, msd_calc, all_msds

In [58]:
d = {'Frame': [1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
     'Track_ID': [1, 1, 1, 1, 1, 2, 2, 2, 2, 2],
     'X': [5, 6, 7, 8, 9, 1, 2, 3, 4, 5],
     'Y': [6, 7, 8, 9, 10, 2, 3, 4, 5, 6]}
df = pd.DataFrame(data=d)
all_msds(df)

array([  0.,   2.,   8.,  18.,  32.,   0.,   2.,   8.,  18.,  32.])

In [59]:
type(df)

pandas.core.frame.DataFrame

In [60]:
type([4, 5, 6])

list

In [65]:
type(df['Frame'])

pandas.core.series.Series

In [24]:
d = {'Frame': ['yes'],
     'Track_ID': ['yes'],
     'X': ['yes'],
     'Y': ['yes']}
df = pd.DataFrame(data=d)
all_msds(df)

array([ 0.])

In [68]:
df['X'].dtype

dtype('int64')

In [69]:
np.dtype('int64')

dtype('int64')

In [34]:
type(4)

int

In [47]:
d = {'Frame': [1, 2, 3, 4, 5],
             'X': [5, 6, 7, 8, 9],
             'Y': [6, 7, 8, 9, 10]}
df = pd.DataFrame(data=d)
msd_calc(df)

array([  0.,   2.,   8.,  18.,  32.])

In [50]:
np.array([0, 2, 8, 18, 32]).astype('float64') == msd_calc(df)

array([ True,  True,  True,  True,  True], dtype=bool)

In [52]:
import numpy.testing as npt

In [ ]:
npt.assert_equal()

In [53]:
d = {'Frame': [1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
     'Track_ID': [1, 1, 1, 1, 1, 2, 2, 2, 2, 2],
     'X': [5, 6, 7, 8, 9, 1, 2, 3, 4, 5],
     'Y': [6, 7, 8, 9, 10, 2, 3, 4, 5, 6]}
df = pd.DataFrame(data=d)

array([  0.,   2.,   8.,  18.,  32.,   0.,   2.,   8.,  18.,  32.])

In [54]:
np.array([0., 2., 8., 18., 32., 0., 2., 8., 18., 32.]).astype('float64') == all_msds(df)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [74]:
d = {'col1': [1, 2, 3, 4, 5]}
df = pd.DataFrame(data=d)

test_d = {'col1': [1, 1, 1, 1]}
test_df = pd.DataFrame(data=test_d)


test_df['col1']

0    1
1    1
2    1
3    1
Name: col1, dtype: int64

In [75]:
nth_diff(df['col1'], 1)

0    1
1    1
2    1
3    1
Name: col1, dtype: int64

In [77]:
pdt.assert_series_equal(nth_diff(df['col1'], 1), test_df['col1'])